api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

app_name = 'api'

urlpatterns = [
    url(r'jobs/(?P<slug>\w+)$' ,views.Jobsviews.as_view(), name="api_jobs"),
    url(r'company/(?P<slug>\w+)$' ,views.Company_views.as_view(), name="api_comapny"),
    url(r'user/(?P<id>\w+)$' ,views.Users_views.as_view(), name="api_users"),
    ]

app/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index),
    url(r'^jobs-$', views.jobs, name='jobs'),
    url(r'^jobs/(?P<slug>[\w-]+)/$', views.job_detail, name='job_detail'),
    url(r'^job/save_job/$', views.job_detail, name='save_job'),
    url(r'^jobs/company/(?P<slug>[\w-]+)/$', views.job_at_company, name='job_at_company'),
    url(r'^company/(?P<slug>[\w-]+)/$', views.company_detail, name='company_detail'),
    url(r'^login/$', views.signin, name='login'),
    url(r'^profile/(?P<user>[\w-]+)/$', views.profile, name='profile'),
    url(r'^register/$', views.signup, name='register'),
    url(r'^resumes/$', login_required(views.resumes), name='resumes'),
    url(r'^resume/(?P<slug>[\w-]+)/$', login_required(views.resume_view), name='resume_view'),
    url(r'^resumes/new/$', login_required(views.upload_resume), name='upload_resume'),
    # others pages url
    url(r'how-it-works/$', views.how_it_works, name='how_it_works'),
]

lazher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('app.urls', namespace="app")),
    url(r'^logout/$', logout, name ='logout'),
    url(r'^api/',include('api.urls', namespace="api")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/company_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load thumbnail %}
<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url() repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax">
			</div>
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>{{company.title|capfirst}}</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
</section>
<section>
		<div class="block">
			<div class="container">
				<div class="row">
				 	<div class="col-lg-12 column">
				 		<div class="job-single-sec style3">
				 			<div class="job-head-wide">
				 				<div class="row">
				 					<div class="col-lg-10">
				 						<div class="job-single-head3 emplye">
							 				<div class="job-thumb"> <img src="{{company.logo.url}}" alt="{{company.title}}" /></div>
							 				<div class="job-single-info3">
							 					<h3>{{company.title}}</h3>
							 					<span><i class="la la-map-marker"></i>{{company.city}}</span>
							 					<ul class="tags-jobs">
								 					<li><i class="la la-file-text"></i> Jobs {{jobs.count}}</li>
								 					<li><i class="la la-eye"></i> Views 5683</li>
								 				</ul>
							 				</div>
							 			</div>
				 					</div>
				 					<div class="col-lg-2">
				 						<div class="share-bar">
							 				<a href="#" title="" class="share-google"><i class="fab fa-google-plus-g"></i></a>
							 				<a href="#" title="" class="share-fb"><i class="fab fa-facebook-f"></i></a>
							 				<a href="#" title="" class="share-twitter"><i class="fab fa-twitter"></i></a>
							 			</div>
								 		<div class="emply-btns">
								 			<a class="seemap" href="#" title=""><i class="la la-map-marker"></i> See On Map</a>
								 			<a class="followus" href="#" title=""><i class="la la-paper-plane"></i> Follow us</a>
								 		</div>
				 					</div>
				 				</div>
				 			</div>
				 			<br>
				 			<div class="job-wide-devider">
							 	<div class="row">
							 		<div class="col-lg-8 column">	
							 			<div class="job-details">
							 				<h3>About {{company.title}}</h3>
							 				{{company.Description|safe|linebreaks}}
							 			</div>
								 		<div class="recent-jobs">
							 				<h3>Jobs from {{company.title}}</h3>
							 				<div class="job-list-modern">
											 	<div class="job-listings-sec no-border">
													{% for i in jobs %}
													<div class="job-listing wtabs noimg">
														<div class="job-title-sec">
															<h3><a href="#" title="">{{i.title}}</a></h3>
															<span>{{i.office.company.title}}</span>
															<div class="job-lctn"><i class="la la-map-marker"></i>{{i.office.company.city}}</div>
														</div>
														<div class="job-style-bx">
															<span class="job-is pt ">{{i.job_type}}</span>
															<span class="fav-job"><i class="la la-heart-o"></i></span>
															<i>{{i.created}}</i>
														</div>
													</div>
													{% endfor %}
												</div>
											 </div>
							 			</div>
							 		</div>
							 		<div class="col-lg-4 column">
							 			<div class="job-overview">
								 			<h3>Company Information</h3>
								 			<ul>
								 				<li><i class="la la-eye"></i><h3>Viewed </h3><span>164</span></li>
								 				<li><i class="la la-file-text"></i><h3>Posted Jobs</h3><span>{{jobs.count}}</span></li>
								 				<li><i class="la la-map"></i><h3>Location</h3><span>{{company.country.name}}, {{company.city}}</span></li>
								 				<li><i class="la la-bars"></i><h3>Categories</h3><span>Arts, Design, Media</span></li>
								 				<li><i class="la la-clock-o"></i><h3>Since</h3><span>{{company.since}}</span></li>
								 				<li><i class="la la-users"></i><h3>Team Size</h3><span>15</span></li>
								 				<li><i class="la la-user"></i><h3>Followers</h3><span>15</span></li>
								 			</ul>
								 		</div>
								 		<div class="quick-form-job">
								 			<h3>Contact Business Network</h3>
								 			<form>
								 				<input type="text" placeholder="Enter your Name *" />
								 				<input type="text" placeholder="Email Address*" />
								 				<input type="text" placeholder="Phone Number" />
								 				<textarea placeholder="Message should have more than 50 characters"></textarea>
								 				<button class="submit">Send Email</button>
								 				<span>You accepts our <a href="#" title="">Terms and Conditions</a></span>
								 			</form>
								 		</div>
							 		</div>
							 	</div>
							 </div>
					 	</div>
				 	</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load marktags %}
{% load static %}
<section>
	<div class="block no-padding">
		<div class="container fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="main-featured-sec">
						<ul class="main-slider-sec text-arrows">
							<li class="slideHome"><img src="{% static 'images/resource/slider1.jpg' %}" alt="" /></li>
							<li class="slideHome"><img src="{% static 'images/resource/slider2.jpg' %}" alt="" /></li>
							<li class="slideHome"><img src="{% static 'images/resource/slider3.jpg' %}" alt="" /></li>
						</ul>
						<div class="job-search-sec">
							<div class="job-search">
								<h3>The Easiest Way to Get Your New Job</h3>
								<span>Find Jobs, Employment & Career Opportunities</span>
								<form action="jobs-" method="GET">
									<div class="row">
										<div class="col-lg-7 col-md-5 col-sm-12 col-xs-12">
											<div class="job-field">
												<input type="text" placeholder="Job title, keywords or company name" name="keywords" />
												<i class="la la-keyboard-o"></i>
											</div>
										</div>
										<div class="col-lg-4 col-md-5 col-sm-12 col-xs-12">
											<div class="job-field">
												<input type="text" placeholder="City, province or region" name="location" />
												<i class="la la-map-marker"></i>
											</div>
										</div>
										<div class="col-lg-1 col-md-2 col-sm-12 col-xs-12">
											<button type="submit"><i class="la la-search"></i></button>
										</div>
									</div>
								</form>
								<div class="or-browser">
									<span>Browse job offers by</span>
									<a href="#" title="">Category</a>
								</div>
							</div>
						</div>
						<div class="scroll-to">
							<a href="#scroll-here" title=""><i class="la la-arrow-down"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="block double-gap-top double-gap-bottom">
		<div data-velocity="-.1" style="background: url(&quot;images/resource/parallax1.jpg&quot;) 50% -56px repeat scroll transparent;" class="parallax scrolly-invisible layer color"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="simple-text-block">
						<h3>Make a Difference with Your Online Resume!</h3>
						<span>Your resume in minutes with JobHunt resume assistant is ready!</span>
						<a href="#" title="">Create an Account</a>
					</div>
				</div>
			</div>
		</div>	
	</div>
</section>
<section>
	<div class="block no-padding">
		<div class="container fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="simple-text">
						<h3>Gat a question?</h3>
						<span>We're here to help. Check out our FAQs, send us an email or call us at 1 (800) 555-5555</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

app/templates/job_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load thumbnail %}
<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url({{jobs.company.logo.url}}) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div>
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>{{jobs.title|capfirst}}</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
</section>
<section>
		<div class="block">
			<div class="container">
				<div class="row">
				 	<div class="col-lg-8 column">
				 		<div class="job-single-sec">
				 			<div class="job-single-head2">
				 				<div class="job-title2"><h3>{{jobs.title}}</h3><span class="job-is ft">{{jobs.job_type}}</span><i class="la la-heart-o"></i></div>
				 				<ul class="tags-jobs">
				 					<li><i class="la la-map-marker"></i>{{jobs.office.company.city}}</li>
				 					<li><i class="la la-money"></i> Monthly Salary : <span>{{jobs.salery}}</span></li>
				 					<li><i class="la la-calendar-o"></i> Post Date: {{jobs.created|date:"F d Y"}} </li>
				 				</ul>
				 				<span><strong>Roles</strong> : 
				 					Coming Soon
				 				</span>
				 			</div>
				 			<div class="job-details">
				 				<h3>Job Description</h3>
				 				{{jobs.Description|safe|linebreaks}}
				 			</div>	
				 			<div class="share-bar">
				 				<span>Share</span><a href="#" title="" class="share-fb"><i class="fa fa-facebook"></i></a><a href="#" title="" class="share-twitter"><i class="fa fa-twitter"></i></a>
				 			</div>
				 		</div>
				 	</div>
				 	<div class="col-lg-4 column">
				 		<div class="job-single-head style2">
			 				<div class="job-thumb">
			 					{% thumbnail jobs.office.company.logo "124x124" crop="center" as im %}
			 					<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
								{% endthumbnail %}
							</div>
			 				<div class="job-head-info">
			 					<h4>{{jobs.office.company.title|capfirst}}</h4>
			 					<span>{{jobs.office.city}}</span>
			 					<p><i class="la la-unlink"></i>{{jobs.office.company.website}}</p>
			 					<p><i class="la la-phone"></i> +90 538 963 54 87</p>
			 					<p><i class="la la-envelope-o"></i>{{jobs.office.company.email}}</p>
			 				</div>
			 				<a href="#" title="" class="apply-job-btn"><i class="la la-paper-plane"></i>Apply for job</a>
			 				<a href="/jobs/company/{{jobs.office.company.slug}}" title="" class="viewall-jobs">View all Jobs</a>
			 			</div>
				 	</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

app/templates/jobs.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
{% load static %}
<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url({% static 'images/resource/slider1.jpg' %}) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div>
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header wform">
							<div class="job-search-sec">
								<div class="job-search">
									<h4>Explore Thousand Of Jobs With Just Simple Search...</h4>
									<form method="GET" action="jobs-">
										<div class="row">
											<div class="col-lg-7">
												<div class="job-field">
													<input value="{{query}}" name="keywords" type="text" placeholder="Job title, keywords or company name" />
													<i class="la la-keyboard-o"></i>
												</div>
											</div>
											<div class="col-lg-4">
												<div class="job-field">
													<input value="{{location}}" type="text" placeholder="City, province or region" name="location" />
													<i class="la la-map-marker"></i>
												</div>
											</div>
											<div class="col-lg-1">
												<button type="submit"><i class="la la-search"></i></button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</section>
<section>
		<div class="block">
			<div class="container">
				 <div class="row">
				 	<div class="col-lg-12">
				 		<span class="emlthis"><a href="mailto:example.com" title=""><i class="la la-envelope-o"></i> Email me Jobs Like These</a></span>
				 		<div class="filterbar">
				 			<h5>{{items.count}} Jobs &amp; Vacancies</h5>
				 			<div class="sortby-sec">
				 				<span>Sort by</span>
				 				<select data-placeholder="Most Recent" class="chosen" style="display: none;">
									<option>Most Recent</option>
									<option>Most Recent</option>
									<option>Most Recent</option>
									<option>Most Recent</option>
								</select>
								<select data-placeholder="20 Per Page" class="chosen" style="display: none;">
									<option>30 Per Page</option>
									<option>40 Per Page</option>
									<option>50 Per Page</option>
									<option>60 Per Page</option>
								</select>
				 			</div>
				 		</div>
				 		<div class="job-grid-sec">
							<div class="row">
								{% for i in items %}
								<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
									<div class="job-grid border">
										<div class="job-title-sec">
											<div class="c-logo"> {% thumbnail i.office.company.logo "235x115" corp="centre" format="PNG" as im %} <center><img src="{{ im.url }}"></center> {% endthumbnail %} </div>
											<h3><a href="/jobs/{{i.slug}}" title="">{{i.office.title}}</a></h3>
											<span>{{i.office.company.title}}</span>
											<span class="fav-job"><i class="la la-heart-o"></i></span>
										</div>
										<span class="job-lctn">{{i.office.company.city}}</span>
										<a href="/jobs/{{i.slug}}" title="">APPLY NOW</a>
									</div>
								</div>
								{% endfor %}
							</div>
						</div>
				 	</div>
				 </div>
			</div>
		</div>
</section>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load subtractify %}
<section class="overlape">
	<div class="block no-padding">
		<div data-velocity="-.1" style="background: url(% static 'images/resource/slider2.jpg' %}) 50% -76.3px repeat scroll transparent;" class="parallax scrolly-invisible no-parallax"></div>
		<div class="container fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="inner-header">
						<div class="container">
							<div class="row">
								<div class="col-lg-6">
									<div class="text-socail">
										<a href="#" title=""><i class="fab fa-facebook-f"></i></a>
										<a href="#" title=""><i class="fab fa-twitter"></i></a>
										<a href="#" title=""><i class="fab fa-instagram"></i></a>
										<a href="#" title=""><i class="fab fa-pinterest-p"></i></a>
										<a href="#" title=""><i class="la la-dribbble"></i></a>
										<a href="#" title=""><i class="la la-google"></i></a>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="action-inner style2">
										<div class="download-cv">
							 				<a href="/media/{{cv.cv}}" title="">Download CV <i class="la la-download"></i></a>
							 			</div>
										<a href="#" title=""><i class="la la-map-marker"></i>{{profile.userprofile.city}} / {{profile.userprofile.country.name}}</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="overlape">
	<div class="block remove-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="cand-single-user">
						<div class="share-bar circle"></div>
			 			<div class="can-detail-s">
			 				<div class="cst"><img src="{{profile.userprofile.avatar.url}}" alt=""></div>
			 				<h3>{{profile.first_name}} {{profile.last_name}}</h3>
			 				{% if experience %}
			 				<span><i>{{experience.0.job_title}}</i> at {{experience.0.company}}</span>
			 				{% else %}
			 					<p>No Working History</p>
			 				{% endif %}
			 				<p>{{profile.email}}</p>
			 				<p>Member Since, {{profile.userprofile.created|date:"Y"}}</p>
			 				<p><i class="la la-map-marker"></i>{{profile.userprofile.city}} / {{profile.userprofile.country.name}}</p>
			 				<div class="skills-badge">
			 					<span>Photoshop</span><span>Designer</span><span>Ilustrator</span>
			 				</div>
			 			</div>
			 			<div class="download-cv"></div>
			 		</div>
			 		<div class="cand-details-sec">
			 			<div class="row no-gape">
			 				<div class="col-lg-9 column">
			 					<div class="cand-details">
			 						<div class="job-overview style2">
							 			<ul>
							 				<li><i class="la la-money"></i><h3>Offerd Salary</h3><span>£15,000 - £20,000</span></li>
							 				<li><i class="la la-mars-double"></i><h3>Gender</h3><span>{{profile.userprofile.gender}}</span></li>
							 				<li><i class="la la-thumb-tack"></i><h3>Career Level</h3><span>Executive</span></li>
							 				<li><i class="la la-puzzle-piece"></i><h3>Industry</h3><span>Management</span></li>
							 				<li><i class="la la-shield"></i><h3>Experience</h3><span>
							 				{% if experience.count == 0 %} 
							 					0 Years
							 				{% else %} 
							 					{% subtractify experience.last.job_from experience.0.job_to %} Years
							 				{% endif %}
							 				</span></li>
							 				<li><i class="la la-line-chart "></i><h3>Qualification</h3><span>{% if education %} {{education.0.degree}} Degree {% else %} No Education History {% endif %}</span></li>
							 			</ul>
							 		</div>
							 		<h2>Candidates About</h2>
			 						{{profile.userprofile.about|safe}}
			 						<div class="edu-history-sec">
			 							<h2>Education</h2>
			 							{% if education.count == 0 %}
			 							<p>No Education History</p>
			 							{% else %}
				 							{% for i in education %}
				 							<div class="edu-history">
				 								<i class="la la-graduation-cap"></i>
				 								<div class="edu-hisinfo">
				 									<h3>{{i.education_level}}</h3>
				 									<i>{{i.year}}</i>
				 									<span>{{i.school.name}} 
				 										<i>{{i.degree}}</i>
				 									</span>
				 									<p>{Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a ipsum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
				 								</div>
				 							</div>
				 							{% endfor %}
			 							{% endif %}
			 						</div>
			 						<div class="edu-history-sec">
			 							<h2>Work &amp; Experience</h2>
			 							{% if experience.count == 0 %}
				 							<p>No Education History</p>
				 							{% else %}
					 							{% for i in experience %}
						 							<div class="edu-history style2">
						 								<i></i>
						 								<div class="edu-hisinfo">
						 									<h3>{{i.job_title}} <span>{{i.company.title}}</span></h3>
						 									<i>{{i.job_from}} - {{i.job_to}}</i>
						 									<p>{{i.experience_description}}</p>
						 								</div>
						 							</div>
					 							{% endfor %}
			 							{% endif %}
			 						</div>
			 						<div class="progress-sec">
			 							<h2>Professional Skills</h2>
			 							<div class="progress-sec style2">
			 								<span>Adobe Photoshop</span>
			 								<div class="progressbar"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i> 
			 									<div class="progress"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div> 
			 								</div>
			 								<p>80%</p>
			 							</div>
			 							<div class="progress-sec style2">
			 								<span>Production In Html</span>
			 								<div class="progressbar"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i> 
			 									<div class="progress"><i></i><i></i><i></i><i></i><i></i></div> 
			 								</div>
			 								<p>50%</p>
			 							</div>
			 							<div class="progress-sec style2">
			 								<span>Graphic Design</span>
			 								<div class="progressbar"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i> 
			 									<div class="progress"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div> 
			 								</div>
			 								<p>100%</p>
			 							</div>
			 						</div>
			 						<div class="edu-history-sec">
			 							<h2>Awards</h2>
			 							{% if awards.count == 0 %}
				 							<p>No Awards</p>
				 							{% else %}
					 							{% for i in awards %}
						 							<div class="edu-history style2">
						 								<i></i>
						 								<div class="edu-hisinfo">
						 									<h3>{{i.company}}</h3>
						 									<i>{{i.year}}</i>
						 									<p>{{i.award_description}}</p>
						 								</div>
						 							</div>
				 							{% endfor %}
			 							{% endif %}
			 						</div>
			 					</div>
			 				</div>
			 				<div class="col-lg-3 column">
					 			<div class="job-overview style3">
						 			<ul>
						 				<li><i class="la la-briefcase"></i><h3>Candidates About</h3></li>
						 				<li><i class="la la-graduation-cap"></i><h3>Education</h3></li>
						 				<li><i class="la la-file-text"></i><h3>Work Experience</h3></li>
						 				<li><i class="la la-puzzle-piece"></i><h3>Portfolio</h3></li>
						 				<li><i class="la la-thumb-tack"></i><h3>Professional Skills</h3></li>
						 				<li><i class="la la-line-chart "></i><h3>Awards</h3></li>
						 				<li><i class="la la-user "></i><h3>Companies Followed By</h3></li>
						 			</ul>
						 			<a href="/media/{{cv.cv}}" title="" class="save-resume">Save Resume</a>
						 			<a href="#" title="" class="contct-user">Contact David</a>
						 		</div>
					 		</div>
			 			</div>
			 		</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

app/templates/resumes.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row search-form">
	<form action="{% url 'app:jobs' %}" method="get">
		<article class="small-12 medium-5 columns search-form-column">
			<div class="search-input-container">
				<input class="search-input keywords ui-autocomplete-input" data-autocomplete="keywords" id="header-keywords" name="keywords" placeholder="Job Title, Skills, or Company" type="text" value="{{query|capfirst}}" autocomplete="off"><span class="clear-field"></span>
				<label class="input-icon fa fa-search" for="header-keywords">
					<span class="small-screen-search">Search</span>
				</label>
			</div>
		</article>
		<article class="small-12 medium-5 columns search-form-column">
			<div class="search-input-container">
				<input class="search-input location" data-autocomplete="location" id="header-location" name="location" placeholder="City, State or ZIP" type="text" value="{{location}}"><span class="clear-field" style="display: none;"></span>
				<label class="input-icon fa fa-location-arrow" for="header-location">
					<span class="accessibility-hide-text">Location</span>
				</label>
			</div>
		</article>
		<article class="small-12 medium-2 columns search-form-column">
			<input class="btn search-jobs" data-gtm="header_search_form_find_jobs_btn_clicked" type="submit" value="Find Jobs">
		</article>
	</form>
</div>
{% if message %}
<span id="messagebox">
    <table id="MXMessageBoxError" cellspacing="4" cellpadding="0" align="Center" border="0" style="">
        <tbody>
            <tr>
                <td valign="top"></td>
                <td valign="top" style="text-align: center;">
                    <span style="color: rgb(221, 77, 57); font-weight: 700; font-size: 16px;">{{message}}</span>
                </td>
            </tr>
        </tbody>
    </table>
</span>
{% endif %}
<div class="main-body" id="main-content">
	<div class="page-header">
		<div class="row">
			<div class="small-12 columns">
				<h1>Your Resumes</h1>
			</div>
		</div>
	</div>
	<div class="your-resumes">
		{% if resumes.count < 1 %}
		<div class="blank-slate bump row">
			<div class="small-12 columns">
				<h3>You haven't added a resume yet</h3>
			</div>
		<div class="small-12 columns margin-below">Recruiters or future employers could be looking for you.</div>
			<div class="small-12 medium-6 large-4 columns end">
				<a class="btn" id="post-new-resume" href="/resumes/new">Add a New Resume</a>
			</div>
		</div>
		{% else %}
		<div class="row">
			<div class="small-12 columns">
				<div class="card with-padding">
					{% for i in resumes %}
					<div class="resume-container">
						<div class="row">
							<div class="small-10 columns">
								<h3><a href="/resume/{{i.slug}}">{{i.job_title}}</a></h3>
							</div>
							<div class="small-2 columns text-right">
								<a class="delete-resume font-icon" href="/resumes/{{i.slug}}">
									<i class="fa fa-times" title="Delete"></i>
								</a>
							</div>
						</div>
						<div class="row">
							<div class="small-12 columns">Updated: {{i.updated}}</div>
						</div>
						{% if not resumes.last.job_title == i.job_title %}
								<hr>
						{% endif %}
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="bump row">
			<div class="small-12 medium-6 large-4 columns end">
				<a class="btn secondary" id="post-new-resume" href="/resumes/new">Add a New Resume</a>
			</div>
		</div>
		{% endif %}
	</div>
	<div class="" data-remodal-id="delete-error-modal" id="delete-error-modal">
		<button class="remodal-close" data-remodal-action="close">
			<span class="accessibility-hide-text">Close</span>
		</button>
		<div class="row">
			<div class="small-12 columns">
				<p>There was an error deleting your resume.</p>
			</div>
		</div>
		<div class="row">
			<div class="small-12 columns">
				<button class="btn" data-remodal-action="confirm">Ok</button>
			</div>
		</div>
	</div>
</div>
{% endblock %}